services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    depends_on:
      - database
    environment:
      MONGO_URI: mongodb://database:27017/grammar-db

  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"